const test = require("node:test");
const assert = require("node:assert/strict");
const mongoose = require("mongoose");
const ItemV2 = require("../models/itemV2.model");
const ItemEdition = require("../models/itemEdition.model");
const ItemRevisionV2 = require("../models/itemRevisionV2.model");
const { clonePresentationForFork, validatePresentationAgainstNamespace } = require("../services/itemV2Presentation.service");
function id() { return new mongoose.Types.ObjectId(); }
function namespaceRevisionFixture() { return { durationTypes: [{ definitionId: "dur-short" }], languageLevels: [{ definitionId: "lang-simple" }], presentationAspects: [{ definitionId: "aspect-humorous" }], selectionSignals: [{ definitionId: "signal-highlight" }] }; }
function revisionFixture() { const variantId = id(); const representationId = id(); return { label: "Opera", authorCredits: ["Autore"], metadata: { license: "CC BY" }, selectionSignals: [{ definitionId: "signal-highlight", weight: 1 }], presentationVariants: [{ _id: variantId, key: "standard", label: "Standard", presentationAspects: [{ definitionId: "aspect-humorous", weight: 0.2 }], representations: [{ _id: representationId, durationTypeDefinitionId: "dur-short", languageLevelDefinitionId: "lang-simple", locale: "it-IT", text: "Testo" }] }], defaultPresentation: { variantId, representationId } }; }
test("Item v2 is museum-neutral", () => { const doc = new ItemV2({ primarySubjectId: id(), ownerType: "user", ownerId: id(), createdBy: id() }); assert.equal(doc.museumId, undefined); assert.equal(doc.itemType, undefined); assert.equal(doc.workingRevisionId, undefined); assert.equal(doc.publishedRevisionId, undefined); });
test("ItemEdition owns Item x Namespace revision lineage", () => { const edition = new ItemEdition({ itemId: id(), namespaceId: id(), createdBy: id() }); assert.ok(edition.itemId); assert.ok(edition.namespaceId); assert.equal(ItemEdition.schema.indexes().some(([keys, options]) => keys.itemId === 1 && keys.namespaceId === 1 && options.unique), true); });
test("ItemRevision v2 separates locale from LanguageLevel", () => { const revision = new ItemRevisionV2({ itemEditionId: id(), version: 1, authoredAgainstNamespaceRevisionId: id(), ...revisionFixture(), createdBy: id(), updatedBy: id() }); const rep = revision.presentationVariants[0].representations[0]; assert.equal(rep.locale, "it-IT"); assert.equal(rep.languageLevelDefinitionId, "lang-simple"); assert.equal(revision.recognitionImage, undefined); });
test("presentation integrity accepts valid definition ids", () => { assert.deepEqual(validatePresentationAgainstNamespace(revisionFixture(), namespaceRevisionFixture()), []); });
test("presentation integrity rejects invalid publish fallback", () => { const revision = revisionFixture(); revision.presentationVariants[0].representations[0].durationTypeDefinitionId = "missing"; revision.authorCredits = []; revision.metadata = {}; revision.defaultPresentation = null; const issues = validatePresentationAgainstNamespace(revision, namespaceRevisionFixture()); for (const code of ["UNKNOWN_DURATION_TYPE", "AUTHOR_REQUIRED", "LICENSE_REQUIRED", "DEFAULT_PRESENTATION_REQUIRED"]) assert.ok(issues.some((issue) => issue.code === code)); });
test("fork clone regenerates local ids and default mapping", () => { const source = revisionFixture(); const cloned = clonePresentationForFork(source); assert.notEqual(String(cloned.presentationVariants[0]._id), String(source.presentationVariants[0]._id)); assert.notEqual(String(cloned.presentationVariants[0].representations[0]._id), String(source.presentationVariants[0].representations[0]._id)); assert.equal(String(cloned.defaultPresentation.variantId), String(cloned.presentationVariants[0]._id)); assert.equal(String(cloned.defaultPresentation.representationId), String(cloned.presentationVariants[0].representations[0]._id)); });
