const test=require("node:test");
const assert=require("node:assert/strict");
const{featureMatchScore,relationCoherence,pruneBeam,scoreCurrentGoals,goalResolution}=require("../services/visitGeneratorSemantics.service");
const{candidateNovelty,skipEvidence,acceptedRefs}=require("../services/interestProfile.service");
const{validateGenerationRequest}=require("../services/validation/generation.validation");

function emptyRevision(overrides={}){return{semanticRefs:[],tags:[],selectionSignals:[],...overrides}}
function emptyVariant(overrides={}){return{semanticFocus:[],presentationAspects:[],...overrides}}
function graphWithEdge({from="a",to="b",viewKey="made_by",baseRelationTypeKey="made_by",semanticRefs=[],traversalWeight=1}={}){return{nodes:new Map([["a",{}],["b",{}],["c",{}]]),canonicalIndex:new Map(),edgesFrom:new Map([[String(from),[{fromItemId:from,toItemId:to,viewKey,baseRelationTypeKey,semanticRefs,traversalWeight,generated:false}]]])}}

test("un goal corrente sull Item ha matching pieno",()=>{assert.equal(featureMatchScore({feature:{kind:"item",itemId:"item-a"},item:{_id:"item-a",itemType:"artwork"},revision:emptyRevision(),variant:emptyVariant(),vocabulary:{},graph:{edgesFrom:new Map()}}),1)});
test("un goal avoid esclude una feature corrispondente",()=>{const result=scoreCurrentGoals({goals:{semanticGoals:[{key:"g",priority:"avoid",weight:1,feature:{kind:"tag",key:"war"}}],relationGoals:[]},item:{_id:"a",itemType:"artwork"},revision:emptyRevision({tags:["war"]}),variant:emptyVariant(),vocabulary:{},graph:{edgesFrom:new Map()}});assert.deepEqual(result.avoidHits,["g"])});
test("semanticRefs di ItemType consentono matching cross museum",()=>{const score=featureMatchScore({feature:{kind:"canonical",scheme:"wikidata",refId:"Q5"},item:{_id:"a",itemType:"local_artist"},revision:emptyRevision(),variant:emptyVariant(),vocabulary:{itemTypeDefinitions:[{key:"local_artist",semanticRefs:[{scheme:"wikidata",id:"Q5",matchType:"close"}]}],selectionSignals:[]},graph:{edgesFrom:new Map()}});assert.ok(score>0)});
test("semanticRefs di PresentationAspect partecipano al matching canonico",()=>{const score=featureMatchScore({feature:{kind:"canonical",scheme:"shared",refId:"anecdotal"},item:{_id:"a",itemType:"artwork"},revision:emptyRevision(),variant:emptyVariant({presentationAspects:[{key:"stories",weight:.9}]}),vocabulary:{itemTypeDefinitions:[],presentationAspects:[{key:"stories",semanticRefs:[{scheme:"shared",id:"anecdotal",matchType:"exact"}]}],selectionSignals:[]},graph:{edgesFrom:new Map()}});assert.ok(score>.5)});
test("semanticRefs di RelationType arrivano dal grafo persistente",()=>{const graph=graphWithEdge({semanticRefs:[{scheme:"shared",id:"creator",matchType:"exact"}],traversalWeight:1});const score=featureMatchScore({feature:{kind:"canonical",scheme:"shared",refId:"creator"},item:{_id:"a",itemType:"artwork"},revision:emptyRevision(),variant:emptyVariant(),vocabulary:{itemTypeDefinitions:[],relationTypes:[{key:"made_by",semanticRefs:[{scheme:"shared",id:"creator",matchType:"exact"}]}],selectionSignals:[]},graph});assert.ok(score>.5)});
test("SelectionSignal rende risolvibile un criterio editoriale generico",()=>{const score=featureMatchScore({feature:{kind:"selection_signal",key:"highlight"},item:{_id:"a",itemType:"artwork"},revision:emptyRevision({selectionSignals:[{key:"highlight",weight:.8}]}),variant:emptyVariant(),vocabulary:{},graph:{edgesFrom:new Map()}});assert.equal(score,.8)});
test("goalResolution riconosce canonicalRef del vocabolario anche senza Item canonico",()=>{const context={semanticGoals:[{priority:"required",feature:{kind:"canonical",scheme:"shared",refId:"highlight"},weight:1}],relationGoals:[]},graph={nodes:new Map(),canonicalIndex:new Map(),edgesFrom:new Map()},vocabulary={itemTypes:[],relationViews:[],itemTypeDefinitions:[],relationTypes:[],presentationAspects:[],selectionSignals:[{key:"highlight",semanticRefs:[{scheme:"shared",id:"highlight",matchType:"exact"}]}]},resolved=goalResolution({context,graph,vocabulary});assert.equal(resolved.errors.length,0);assert.deepEqual(resolved.requiredKeys,["semantic:0"])});
test("una relazione persistente diretta aumenta la coerenza narrativa",()=>{const left={item:{_id:"a"},revision:emptyRevision()},right={item:{_id:"b"},revision:emptyRevision()},graph=graphWithEdge({from:"a",to:"b",traversalWeight:1});assert.ok(relationCoherence(left,right,graph)>0)});
test("la priorita corrente e lessicografica rispetto alla utility storica",()=>{const states=[{hardCovered:1,explicitScore:.1,utility:100,entries:[],elapsedSeconds:10},{hardCovered:1,explicitScore:.8,utility:-10,entries:[],elapsedSeconds:20}];assert.equal(pruneBeam(states,1,1)[0].explicitScore,.8)});
test("novelty distingue nuova variante da contenuto gia fruito",()=>{const state={exposuresByItem:new Map([["a",[{itemId:"a",variantKey:"standard",semanticFeatureKeys:["item:a"],presentationAspectKeys:[],durationKeys:["short"],languageLevelKeys:["simple"]}] ]])};assert.equal(candidateNovelty(state,{itemId:"a",variantKey:"new",semanticFeatureKeys:[],presentationAspectKeys:[]}).reason,"new_variant");assert.equal(candidateNovelty(state,{itemId:"a",variantKey:"standard",semanticFeatureKeys:["item:a"],presentationAspectKeys:[],durationKey:"short",languageLevelKey:"simple"}).reason,"familiar_content")});
test("skip contestuale non confonde time pressure con disinteresse",()=>{assert.equal(skipEvidence("time_pressure"),0);assert.ok(skipEvidence("not_interested")<-.5)});
test("learning canonico propaga solo exact e close come identita",()=>{assert.deepEqual(acceptedRefs([{scheme:"x",id:"1",matchType:"exact"},{scheme:"x",id:"2",matchType:"close"},{scheme:"x",id:"3",matchType:"broader"}]).map(ref=>ref.id),["1","2"])});
test("GenerationRequest rifiuta interests legacy e accetta semantic goals e spatial constraints",()=>{const errors=validateGenerationRequest({timeBudgetSeconds:600,semanticGoals:[{priority:"preferred",feature:{kind:"tag",key:"renaissance"},weight:1}],spatialConstraints:[]});assert.deepEqual(errors,[]);assert.equal(validateGenerationRequest({timeBudgetSeconds:600,interests:[]}).some(error=>error.code==="REMOVED_FIELD"),true)});
