const express = require("express");
const router = express.Router();
const { requireAuth } = require("../middlewares/auth");
const { validateObjectIdParam } = require("../middlewares/validateObjectIdParam");
const controller = require("../controllers/adaptive.controller");
router.put("/users/me/adaptive-learning", requireAuth, controller.setLearning);
router.get("/users/me/adaptive-profile", requireAuth, controller.profile);
router.delete("/users/me/adaptive-profile", requireAuth, controller.reset);
router.put("/users/me/navigation-preference", requireAuth, controller.setDefaultNavigation);
router.put("/visits/:visitId/navigation-preference", requireAuth, validateObjectIdParam("visitId"), controller.setVisitNavigation);
router.get("/visits/:visitId/logistics-plan", requireAuth, validateObjectIdParam("visitId"), controller.logisticsPlan);
module.exports = router;
