const express = require("express");
const router = express.Router();
const { requireAuth } = require("../middlewares/auth");
const { validateObjectIdParam } = require("../middlewares/validateObjectIdParam");
const controller = require("../controllers/layout.controller");
const validateMuseumId = validateObjectIdParam("museumId");
router.get("/routing-attribute-catalog", controller.catalog);
router.get("/museums/:museumId/layout", validateMuseumId, controller.get);
router.put("/museums/:museumId/layout", requireAuth, validateMuseumId, controller.update);
router.post("/museums/:museumId/layout/check-consistency", requireAuth, validateMuseumId, controller.check);
router.post("/museums/:museumId/layout/request-review", requireAuth, validateMuseumId, controller.review);
router.post("/museums/:museumId/layout/withdraw-review", requireAuth, validateMuseumId, controller.withdraw);
router.post("/museums/:museumId/layout/request-changes", requireAuth, validateMuseumId, controller.changes);
router.post("/museums/:museumId/layout/publish", requireAuth, validateMuseumId, controller.publish);
module.exports = router;
