const express = require("express");
const { requireAuth } = require("../middlewares/auth");
const { validateObjectIdParam } = require("../middlewares/validateObjectIdParam");
const controller = require("../controllers/marketplaceV2.controller");
const authoringController = require("../controllers/marketplaceAuthoringV2.controller");
const preflightController = require("../controllers/marketplaceAuthoringPreflightV2.controller");
const discoveryController = require("../controllers/marketplaceDiscoveryV2.controller");

const router = express.Router();
const listingId = validateObjectIdParam("listingId");
const offerId = validateObjectIdParam("offerId");
const itemId = validateObjectIdParam("itemId");
const namespaceId = validateObjectIdParam("namespaceId");
const physicalVocabularyId = validateObjectIdParam("physicalVocabularyId");
const organizationId = validateObjectIdParam("organizationId");
const editorialContextId = validateObjectIdParam("editorialContextId");
const editorialReleaseId = validateObjectIdParam("editorialReleaseId");
const venueId = validateObjectIdParam("venueId");
const venueTargetId = validateObjectIdParam("venueTargetId");
const visitId = validateObjectIdParam("visitId");
const resourceId = validateObjectIdParam("resourceId");

router.use(requireAuth);
router.get("/v2/marketplace/catalog", controller.catalog);
router.get("/v2/marketplace/venue-selector", controller.venueSelector);
router.get("/v2/marketplace/discovery/organizations", discoveryController.organizations);
router.get("/v2/marketplace/discovery/organizations/:organizationId", organizationId, discoveryController.organization);
router.get("/v2/marketplace/discovery/venues", discoveryController.venues);
router.get("/v2/marketplace/discovery/venues/:venueId", venueId, discoveryController.venue);
router.get("/v2/marketplace/authoring/preflight", preflightController.authoringPreflight);
router.get("/v2/marketplace/venues/:venueId/authoring-targets", venueId, authoringController.venueAuthoringTargets);
router.get("/v2/marketplace/item-authoring/:itemId", itemId, controller.itemAuthoringProjection);
router.get("/v2/marketplace/namespace-authoring/:namespaceId", namespaceId, controller.namespaceAuthoringControls);
router.get("/v2/marketplace/editorial-contexts/:editorialContextId/release-composer", editorialContextId, authoringController.editorialReleaseComposer);
router.get("/v2/marketplace/visit-authoring/new", authoringController.newVisitAuthoring);
router.get("/v2/marketplace/visit-authoring/releases/:editorialReleaseId/content", editorialReleaseId, authoringController.visitAuthoringContent);
router.get("/v2/marketplace/visit-authoring/:visitId", visitId, authoringController.visitAuthoring);
router.get("/v2/marketplace/venue-targets/:venueTargetId/authoring-context", venueTargetId, controller.venueTargetAuthoringContext);
router.get("/v2/marketplace/acquisitions", controller.acquisitionHistory);
router.get("/v2/marketplace/commerce", controller.commercialManagement);
router.get("/v2/marketplace/account-workspace", controller.marketplaceAccountWorkspace);
router.get("/v2/marketplace/management/organizations/:organizationId", organizationId, controller.marketplaceOrganizationDetail);
router.get("/v2/marketplace/management/namespaces/:namespaceId", namespaceId, controller.marketplaceNamespaceManagement);
router.get("/v2/marketplace/management/physical-vocabularies/:physicalVocabularyId", physicalVocabularyId, controller.marketplacePhysicalVocabularyManagement);
router.get("/v2/marketplace/management/venues/:venueId", venueId, controller.marketplaceVenueManagement);
router.get("/v2/marketplace/workspace/context", controller.creatorWorkspaceContext);
router.get("/v2/marketplace/workspace/resources", controller.creatorWorkspaceResources);
router.get("/v2/marketplace/workspace/resources/:resourceType/:resourceId", resourceId, controller.creatorWorkspaceResourceDetail);
router.get("/v2/marketplace/workspace", controller.creatorWorkspace);
router.get("/v2/marketplace/distribution", controller.distributionDashboard);
router.post("/v2/marketplace/workspace/operations", controller.workspaceOperation);
router.post("/v2/marketplace/listings", controller.createListing);
router.get("/v2/marketplace/listings/:listingId", listingId, controller.detail);
router.post("/v2/marketplace/listings/:listingId/offers", listingId, controller.createOffer);
router.post("/v2/marketplace/listings/:listingId/withdraw", listingId, controller.withdrawListing);
router.post("/v2/marketplace/offers/:offerId/acquire", offerId, controller.acquire);
router.post("/v2/marketplace/offers/:offerId/withdraw", offerId, controller.withdrawOffer);

module.exports = router;
