const express=require("express"),router=express.Router(),{requireAuth}=require("../middlewares/auth"),{validateObjectIdParam}=require("../middlewares/validateObjectIdParam"),controller=require("../controllers/visitSessions.controller");
const validateSessionId=validateObjectIdParam("sessionId"),validateProposalId=validateObjectIdParam("proposalId");
router.post("/visit-sessions",requireAuth,controller.start);
router.get("/visit-sessions/:sessionId/plan",requireAuth,validateSessionId,controller.currentPlan);
router.post("/visit-sessions/:sessionId/transitions",requireAuth,validateSessionId,controller.transition);
router.post("/visit-sessions/:sessionId/content-entries/experience",requireAuth,validateSessionId,controller.contentExperience);
router.post("/visit-sessions/:sessionId/physical-targets/observation",requireAuth,validateSessionId,controller.physicalObservation);
router.post("/visit-sessions/:sessionId/interactions",requireAuth,validateSessionId,controller.interaction);
router.post("/visit-sessions/:sessionId/presentation-depth",requireAuth,validateSessionId,controller.presentationDepth);
router.post("/visit-sessions/:sessionId/pause",requireAuth,validateSessionId,controller.pause);
router.post("/visit-sessions/:sessionId/resume",requireAuth,validateSessionId,controller.resume);
router.post("/visit-sessions/:sessionId/route-completed",requireAuth,validateSessionId,controller.routeCompleted);
router.post("/visit-sessions/:sessionId/plan-change-proposals",requireAuth,validateSessionId,controller.proposeChange);
router.post("/plan-change-proposals/:proposalId/accept",requireAuth,validateProposalId,controller.acceptChange);
router.post("/plan-change-proposals/:proposalId/reject",requireAuth,validateProposalId,controller.rejectChange);
router.post("/visit-sessions/:sessionId/complete",requireAuth,validateSessionId,controller.complete);
module.exports=router;
