const policy = require("../config/adaptivePolicy");
const GlobalAdaptiveProfile = require("../models/globalAdaptiveProfile.model");
const MuseumAdaptiveProfile = require("../models/museumAdaptiveProfile.model");

function clamp(value, min, max) { return Math.min(max, Math.max(min, value)); }
function usable(estimate) { return Number.isFinite(estimate?.value) && (Number(estimate.confidence) || 0) >= policy.confidence.usableThreshold; }
function paceBucket(preference = 0.5) { const value = clamp(Number(preference), 0, 1); if (value <= policy.pace.calmMax) return "calm"; if (value >= policy.pace.fastMin) return "fast"; return "normal"; }
function fallbackPaceFactor(preference = 0.5) { const value = clamp(Number(preference), 0, 1); if (value <= 0.5) { const t = value / 0.5; return policy.coldStart.paceFactors.calm + t * (policy.coldStart.paceFactors.normal - policy.coldStart.paceFactors.calm); } const t = (value - 0.5) / 0.5; return policy.coldStart.paceFactors.normal + t * (policy.coldStart.paceFactors.fast - policy.coldStart.paceFactors.normal); }
function blendEstimate(base, estimate, maxWeight = 1) { if (!usable(estimate)) return base; const weight = Math.min(maxWeight, Math.max(0, Number(estimate.confidence) || 0)); return base * (1 - weight) + estimate.value * weight; }
async function loadPopulationProfiles(museumId = null) { const [globalProfile, museumProfile] = await Promise.all([GlobalAdaptiveProfile.findOne({ key: "global" }).lean(), museumId ? MuseumAdaptiveProfile.findOne({ museumId }).lean() : null]); return { globalProfile, museumProfile }; }
function resolveMovementBaseline({ userProfile = null, globalProfile = null }) { let baseline = policy.coldStart.movementSpeedMps; baseline = blendEstimate(baseline, globalProfile?.movementSpeedMps, 0.8); baseline = blendEstimate(baseline, userProfile?.movement?.estimatedSpeedMps, policy.movement.maxHistoricalWeight); return clamp(baseline, policy.movement.minSpeedMps, policy.movement.maxSpeedMps); }
function resolvePaceFactor({ preference = 0.5, globalProfile = null, museumProfile = null }) { const bucket = paceBucket(preference); let factor = fallbackPaceFactor(preference); factor = blendEstimate(factor, globalProfile?.paceFactors?.[bucket], 0.8); factor = blendEstimate(factor, museumProfile?.paceFactors?.[bucket], 0.6); return clamp(factor, 0.4, 1.8); }
function resolveEffectiveSpeed({ preference = 0.5, userProfile = null, globalProfile = null, museumProfile = null }) { const baselineSpeedMps = resolveMovementBaseline({ userProfile, globalProfile }); const paceFactor = resolvePaceFactor({ preference, globalProfile, museumProfile }); const museumFactor = usable(museumProfile?.movementResidualFactor) ? blendEstimate(1, museumProfile.movementResidualFactor, 0.5) : 1; return { baselineSpeedMps, paceFactor, speedMps: clamp(baselineSpeedMps * paceFactor / Math.max(0.5, museumFactor), policy.movement.minSpeedMps, policy.movement.maxSpeedMps), museumMovementFactor: museumFactor }; }
function resolveObservationSeconds({ userProfile = null, globalProfile = null, museumProfile = null, itemProfile = null }) { let seconds = policy.coldStart.observationSeconds; seconds = blendEstimate(seconds, globalProfile?.observationSeconds, 0.8); seconds = blendEstimate(seconds, userProfile?.observation?.typicalPostContentObservationSeconds, 0.7); const museumFactor = usable(museumProfile?.observationFactor) ? blendEstimate(1, museumProfile.observationFactor, 0.6) : 1; const itemFactor = itemProfile && (itemProfile.confidence || 0) >= policy.confidence.usableThreshold ? 1 + (Math.max(0.1, itemProfile.observationFactor || 1) - 1) * Math.min(0.8, itemProfile.confidence) : 1; return Math.max(0, seconds * museumFactor * itemFactor); }

module.exports = { usable, paceBucket, fallbackPaceFactor, blendEstimate, loadPopulationProfiles, resolveMovementBaseline, resolvePaceFactor, resolveEffectiveSpeed, resolveObservationSeconds };
