const Item = require("../models/item.model");
const ItemRevision = require("../models/itemRevision.model");
const SemanticEdge = require("../models/semanticEdge.model");
const VisitRevision = require("../models/visitRevision.model");
const User = require("../models/user");
const AppError = require("../utils/AppError");
const { getMuseumVocabulary } = require("./museumVocabulary.service");
const { assertMuseumRole, hasMuseumRole } = require("./museumAuthorization.service");
const { normalizeItemPayload, validateItemDraftPayload } = require("./validation/item.validation");
const { markRevisionEdited } = require("./revisionWorkflow.service");
const { invalidateVisitsUsingItem } = require("./visitDependency.service");
const {
  getRevisionSemanticEdges,
  getRevisionSemanticEdgesMap,
  replaceRevisionSemanticEdges,
  cloneRevisionSemanticEdges,
  deleteSemanticEdgesForSourceItem,
  semanticEdgeTargetDependency,
  edgeSnapshot,
} = require("./semanticEdge.service");
const { invalidateMuseumSemanticGraphCache } = require("./semanticGraph.service");
const { bumpPublishedGraphEpoch } = require("./semanticGraphState.service");

const REVISION_FIELDS = ["label", "recognitionImage", "tags", "metadata", "semanticRefs", "selectionSignals", "presentationVariants", "defaultPresentation", "jsonld"];
function hasOwn(object, key) { return Object.prototype.hasOwnProperty.call(object || {}, key); }
function rejectManagedFields(payload = {}) {
  const forbidden = ["status", "integrity", "review", "publication", "version", "itemId", "representations"];
  const errors = forbidden.filter((field) => hasOwn(payload, field)).map((field) => ({ field, code: field === "representations" ? "REMOVED_FIELD" : "FORBIDDEN_FIELD", message: field === "representations" ? "representations non e piu un campo diretto: usare presentationVariants" : `${field} e gestito dal backend` }));
  if (hasOwn(payload, "relations")) errors.push({ field: "relations", code: "REMOVED_FIELD", message: "relations embedded non e piu supportato: usare semanticEdges" });
  if (hasOwn(payload, "relationCommands")) errors.push({ field: "relationCommands", code: "REMOVED_FIELD", message: "relationCommands non e supportato: usare semanticEdges" });
  if (errors.length) throw new AppError("Payload non valido", 400, errors);
}
function normalizeSelectionSignals(values) { if (!Array.isArray(values)) return values; return values.map((signal) => signal && typeof signal === "object" ? { key: String(signal.key || "").trim().toLowerCase(), weight: signal.weight === undefined ? 1 : Number(signal.weight) } : signal); }
function normalizedPayload(payload) { const normalized = normalizeItemPayload(payload); if (hasOwn(payload, "selectionSignals")) normalized.selectionSignals = normalizeSelectionSignals(payload.selectionSignals); return normalized; }
function revisionSnapshot(revision) { const source = revision?.toObject ? revision.toObject() : revision || {}; return Object.fromEntries(REVISION_FIELDS.map((field) => [field, source[field]])); }
function workflowSnapshot(revision) { const source = revision?.toObject ? revision.toObject() : revision || {}; return { status: source.status, integrity: source.integrity, review: source.review, publication: source.publication, updatedBy: source.updatedBy }; }
function mergeRevisionPayload(revision, rawPayload, normalized) { const source = revisionSnapshot(revision); for (const field of REVISION_FIELDS) if (hasOwn(rawPayload, field)) source[field] = normalized[field]; return source; }
async function findItemOrFail({ museumId, itemId, includeTrashed = false }) { const query = { _id: itemId, museumId }; if (!includeTrashed) query.lifecycleStatus = "active"; const item = await Item.findOne(query); if (!item) throw new AppError("Item non trovato", 404); return item; }
async function nextVersion(itemId) { const latest = await ItemRevision.findOne({ itemId }).sort({ version: -1 }).select("version").lean(); return (latest?.version || 0) + 1; }
async function createWorkingRevisionFromPublished(item, actorUserId) { if (!item.publishedRevisionId) throw new AppError("Nessuna revisione pubblicata da clonare", 409); const published = await ItemRevision.findById(item.publishedRevisionId); if (!published) throw new AppError("Revisione pubblicata non trovata", 409); const revision = await ItemRevision.create({ itemId: item._id, version: await nextVersion(item._id), basedOnRevisionId: published._id, ...revisionSnapshot(published), status: "draft", integrity: { status: "needs_review", issues: [] }, review: {}, publication: {}, createdBy: actorUserId, updatedBy: actorUserId }); try { await cloneRevisionSemanticEdges({ museumId: item.museumId, sourceItemId: item._id, fromRevisionId: published._id, toRevisionId: revision._id }); item.workingRevisionId = revision._id; await item.save(); return revision; } catch (error) { await SemanticEdge.deleteMany({ sourceItemRevisionId: revision._id }).catch(() => {}); await revision.deleteOne().catch(() => {}); throw error; } }
async function getWorkingRevision(item, actorUserId, { createFromPublished = true } = {}) { if (item.workingRevisionId) { const revision = await ItemRevision.findById(item.workingRevisionId); if (!revision) throw new AppError("Revisione di lavoro non trovata", 409); return revision; } if (createFromPublished && item.publishedRevisionId) return createWorkingRevisionFromPublished(item, actorUserId); throw new AppError("L'Item non ha una revisione di lavoro", 409); }
async function validateDraft({ museumId, itemId = null, itemType, payload, vocabulary, mode }) { const errors = await validateItemDraftPayload({ museumId, itemId, itemType, payload, vocabulary, mode }); if (Array.isArray(payload.selectionSignals)) { const keys = new Set((vocabulary.selectionSignals || []).map((entry) => entry.key)), seen = new Set(); payload.selectionSignals.forEach((signal, index) => { const path = `selectionSignals[${index}]`; if (!signal || typeof signal !== "object" || !keys.has(signal.key)) errors.push({ field: `${path}.key`, code: "UNKNOWN_SELECTION_SIGNAL", message: `SelectionSignal non presente nel vocabolario: ${signal?.key || ""}` }); if (seen.has(signal?.key)) errors.push({ field: `${path}.key`, code: "DUPLICATE_KEY", message: "SelectionSignal duplicato" }); seen.add(signal?.key); if (!Number.isFinite(signal?.weight) || signal.weight < 0 || signal.weight > 1) errors.push({ field: `${path}.weight`, code: "INVALID_NUMBER", message: "weight deve essere tra 0 e 1" }); }); } return errors; }
async function createItem({ museumId, payload, userId }) { await assertMuseumRole({ userId, museumId, minimumRole: "operator" }); rejectManagedFields(payload); const vocabulary = await getMuseumVocabulary(museumId), normalized = normalizedPayload(payload), errors = await validateDraft({ museumId, itemType: normalized.itemType, payload: normalized, vocabulary, mode: "create" }); if (errors.length) throw new AppError("Payload non valido", 400, errors); const item = await Item.create({ externalId: normalized.externalId, museumId, itemType: normalized.itemType, createdBy: userId }); let revision = null; try { const revisionData = Object.fromEntries(REVISION_FIELDS.filter((field) => normalized[field] !== undefined).map((field) => [field, normalized[field]])); revision = await ItemRevision.create({ itemId: item._id, version: 1, ...revisionData, status: "draft", integrity: { status: "needs_review", issues: [] }, createdBy: userId, updatedBy: userId }); const semanticEdges = normalized.semanticEdges || [], edgeErrors = await validateDraft({ museumId, itemId: item._id, itemType: item.itemType, payload: { semanticEdges }, vocabulary, mode: "update" }); if (edgeErrors.length) throw new AppError("Payload non valido", 400, edgeErrors); const edges = await replaceRevisionSemanticEdges({ museumId, sourceItemId: item._id, sourceItemRevisionId: revision._id, semanticEdges }); item.workingRevisionId = revision._id; await item.save(); return { item, revision, semanticEdges: edges.map(edgeSnapshot) }; } catch (error) { if (revision) await SemanticEdge.deleteMany({ sourceItemRevisionId: revision._id }).catch(() => {}); if (revision) await revision.deleteOne().catch(() => {}); await item.deleteOne().catch(() => {}); throw error; } }
async function restoreDraftState({ item, revision, itemBefore, revisionBefore, edgesBefore, museumId }) { await Promise.all([Item.updateOne({ _id: item._id }, { $set: { externalId: itemBefore.externalId ?? null, itemType: itemBefore.itemType } }), ItemRevision.updateOne({ _id: revision._id }, { $set: { ...revisionBefore.payload, ...revisionBefore.workflow } })]); await replaceRevisionSemanticEdges({ museumId, sourceItemId: item._id, sourceItemRevisionId: revision._id, semanticEdges: edgesBefore }); }
async function updateItem({ museumId, itemId, payload, userId }) { await assertMuseumRole({ userId, museumId, minimumRole: "operator" }); rejectManagedFields(payload); const item = await findItemOrFail({ museumId, itemId }), revision = await getWorkingRevision(item, userId); const existingEdges = await getRevisionSemanticEdges(revision._id), edgesBefore = existingEdges.map(edgeSnapshot), itemBefore = { externalId: item.externalId, itemType: item.itemType }, revisionBefore = { payload: revisionSnapshot(revision), workflow: workflowSnapshot(revision) }; try { markRevisionEdited(revision, userId); } catch (error) { throw new AppError(error.message, 409, [{ code: error.code }]); } const normalized = normalizedPayload(payload); if (item.publishedRevisionId && (hasOwn(payload, "externalId") || hasOwn(payload, "itemType"))) throw new AppError("Payload non valido", 409, [{ field: hasOwn(payload, "itemType") ? "itemType" : "externalId", code: "IMMUTABLE_AFTER_PUBLICATION", message: "externalId e itemType non possono cambiare dopo la prima pubblicazione" }]); const effectiveItemType = hasOwn(payload, "itemType") ? normalized.itemType : item.itemType, merged = mergeRevisionPayload(revision, payload, normalized), effectiveEdges = hasOwn(payload, "semanticEdges") ? normalized.semanticEdges : edgesBefore, vocabulary = await getMuseumVocabulary(museumId); const errors = await validateDraft({ museumId, itemId, itemType: effectiveItemType, payload: { ...merged, itemType: effectiveItemType, semanticEdges: effectiveEdges }, vocabulary, mode: "create" }); if (errors.length) throw new AppError("Payload non valido", 400, errors); if (hasOwn(payload, "externalId")) item.externalId = normalized.externalId; if (hasOwn(payload, "itemType")) item.itemType = normalized.itemType; Object.assign(revision, merged); revision.updatedBy = userId; try { await Promise.all([revision.save(), item.save()]); const edges = hasOwn(payload, "semanticEdges") ? await replaceRevisionSemanticEdges({ museumId, sourceItemId: item._id, sourceItemRevisionId: revision._id, semanticEdges: effectiveEdges }) : existingEdges; invalidateMuseumSemanticGraphCache(museumId); return { item, revision, semanticEdges: edges.map(edgeSnapshot) }; } catch (error) { try { await restoreDraftState({ item, revision, itemBefore, revisionBefore, edgesBefore, museumId }); } catch (rollbackError) { throw new AppError("Aggiornamento Item fallito e rollback incompleto", 500, [{ code: "ITEM_GRAPH_ROLLBACK_FAILED", message: rollbackError.message }, { code: "ORIGINAL_ERROR", message: error.message }]); } throw error; } }
async function actorCanManage(actorUserId, museumId) { if (!actorUserId) return false; const user = await User.findOne({ _id: actorUserId, status: "active" }).lean(); return Boolean(user && hasMuseumRole(user, museumId, "operator")); }
async function getItemById({ museumId, itemId, actorUserId = null, view = "published" }) { const item = await findItemOrFail({ museumId, itemId, includeTrashed: view === "working" }), canManage = await actorCanManage(actorUserId, museumId); if (view === "working" && !canManage) throw new AppError("Accesso alla revisione di lavoro non autorizzato", 403); const revisionId = view === "working" && item.workingRevisionId ? item.workingRevisionId : item.publishedRevisionId; if (!revisionId) throw new AppError("Nessuna revisione disponibile", 404); const revision = await ItemRevision.findById(revisionId); if (!revision) throw new AppError("Revisione non trovata", 404); if (!canManage && revision.integrity.status !== "valid") throw new AppError("Item non disponibile", 404); const semanticEdges = await getRevisionSemanticEdges(revision._id); return { item, revision, semanticEdges: semanticEdges.map(edgeSnapshot) }; }
async function listItems({ museumId, filters = {}, actorUserId = null, view = "published" }) { const canManage = await actorCanManage(actorUserId, museumId); if (view === "working" && !canManage) throw new AppError("Accesso alle bozze non autorizzato", 403); const query = { museumId }; if (!canManage || !filters.includeTrashed) query.lifecycleStatus = "active"; if (filters.itemType) query.itemType = filters.itemType; const items = await Item.find(query).sort({ updatedAt: -1 }).lean(); const selected = items.map((item) => ({ item, revisionId: view === "working" && item.workingRevisionId ? item.workingRevisionId : item.publishedRevisionId })).filter((entry) => entry.revisionId); const revisionIds = selected.map((entry) => entry.revisionId), [revisions, edgesByRevision] = await Promise.all([ItemRevision.find({ _id: { $in: revisionIds } }).lean(), getRevisionSemanticEdgesMap(revisionIds)]), revisionById = new Map(revisions.map((revision) => [String(revision._id), revision])), results = []; for (const entry of selected) { const revision = revisionById.get(String(entry.revisionId)); if (!revision) continue; if (filters.status && revision.status !== filters.status) continue; if (filters.integrity && revision.integrity?.status !== filters.integrity) continue; if (!canManage && revision.integrity?.status !== "valid") continue; const semanticEdges = edgesByRevision.get(String(entry.revisionId)) || []; results.push({ item: entry.item, revision, semanticEdges: semanticEdges.map(edgeSnapshot) }); } return results; }
async function markPublishedGraphChanged(museumId) { await bumpPublishedGraphEpoch(museumId); invalidateMuseumSemanticGraphCache(museumId); }
async function trashItem({ museumId, itemId, userId }) { await assertMuseumRole({ userId, museumId, minimumRole: "operator" }); const item = await findItemOrFail({ museumId, itemId }); item.lifecycleStatus = "trashed"; item.trashedAt = new Date(); item.trashedBy = userId; await item.save(); await markPublishedGraphChanged(museumId); await invalidateVisitsUsingItem({ itemId: item._id, code: "VISIT_ITEM_TRASHED", message: "Un Item della visita e stato spostato nel cestino", blocking: true }); return item; }
async function restoreItem({ museumId, itemId, userId }) { await assertMuseumRole({ userId, museumId, minimumRole: "manager" }); const item = await findItemOrFail({ museumId, itemId, includeTrashed: true }); item.lifecycleStatus = "active"; item.trashedAt = null; item.trashedBy = null; await item.save(); await markPublishedGraphChanged(museumId); return item; }
async function hardDeleteItem({ museumId, itemId, userId }) { await assertMuseumRole({ userId, museumId, minimumRole: "manager" }); const item = await findItemOrFail({ museumId, itemId, includeTrashed: true }); if (item.lifecycleStatus !== "trashed") throw new AppError("L'Item deve essere nel cestino prima della cancellazione definitiva", 409); const [visitDependency, edgeDependency, focusDependency] = await Promise.all([VisitRevision.exists({ "contentEntries.itemId": item._id }), semanticEdgeTargetDependency(item._id), ItemRevision.exists({ "presentationVariants.semanticFocus.itemId": item._id })]); if (visitDependency || edgeDependency || focusDependency) throw new AppError("Impossibile eliminare definitivamente: esistono dipendenze attive", 409); await deleteSemanticEdgesForSourceItem(item._id); await ItemRevision.deleteMany({ itemId: item._id }); await item.deleteOne(); await markPublishedGraphChanged(museumId); return item; }
module.exports = { REVISION_FIELDS, findItemOrFail, getWorkingRevision, createItem, updateItem, listItems, getItemById, trashItem, restoreItem, hardDeleteItem };
