const VisitSession=require("../models/visitSession.model");
const SessionPlanRevision=require("../models/sessionPlanRevision.model");
const Proposal=require("../models/plan_change_proposal.model");
const UserGenerationPreference=require("../models/userGenerationPreference.model");
const AppError=require("../utils/AppError");
const{activeElapsedSeconds}=require("./visitSession.service");
const{getCurrentSessionPlan,nextPlanVersion,id}=require("./sessionPlan.service");
const H=require("./planAdaptation.helpers"),R=require("./planAdaptation.request"),C=require("./planAdaptation.compose");
async function rememberGenerationPreferences({userId,payload}){const set={};for(const field of[...R.SCALARS,"semanticGoals","relationGoals","coverageGoal","audience","knowledge","navigationRequirements"])if(payload[field]!==undefined)set[field]=payload[field];if(!Object.keys(set).length)return null;return UserGenerationPreference.findOneAndUpdate({userId},{$set:set},{upsert:true,new:true,runValidators:true,setDefaultsOnInsert:true})}
function canonicalEntryIndex(session,plan,payload={}){const max=Math.max(0,(plan.contentEntries||[]).length-1);const stored=Number(session.currentEntryIndex);const canonical=session.status==="route_completed"?max:Math.min(max,Number.isInteger(stored)?Math.max(0,stored):0);if(payload.currentEntryIndex!==undefined){const asked=Number(payload.currentEntryIndex);if(!Number.isInteger(asked)||asked!==canonical)throw new AppError("currentEntryIndex non coincide con lo stato di esecuzione della sessione",409,[{field:"currentEntryIndex",code:"EXECUTED_PREFIX_MISMATCH",message:`Indice corrente atteso: ${canonical}`}])}return canonical}
async function proposePlanChange({userId,sessionId,payload={}}){const{session,plan}=await getCurrentSessionPlan({sessionId,userId});if(session.status==="paused"&&!["manual_request","refocus_future","parameter_change","route_only"].includes(payload.reason))throw new AppError("Riprendere la visita prima del replanning automatico",409);const index=canonicalEntryIndex(session,plan,payload);if(!plan.contentEntries?.[index])throw new AppError("Contenuto corrente non disponibile",409);const elapsed=activeElapsedSeconds(session),prepared=R.prepareAdaptation({plan,session,payload,currentEntryIndex:index,elapsed}),tail=await C.buildTail({userId,plan,prepared}),composed=C.composeRevision({plan,prepared,tail,currentEntryIndex:index,elapsed});const proposal=await Proposal.create({userId,sessionId:session._id,basePlanRevisionId:plan._id,reason:prepared.reason,fidelity:prepared.fidelity,currentEntryIndex:index,adaptationRequest:payload,currentEstimate:{activeElapsedSeconds:Math.round(elapsed),remainingBudgetSeconds:Math.round(prepared.currentRemaining),requestedRemainingBudgetSeconds:Math.round(prepared.remainingBudget),proposedTotalSessionBudgetSeconds:composed.totalSessionBudgetSeconds,currentPlanRemainingSeconds:Math.round(prepared.originalRemaining),deviationRatio:prepared.ratio},proposedRevision:composed.revision,messageKey:R.messageKey(prepared.reason)});if(["refocus_future","extend_visit"].includes(prepared.reason)){const current=prepared.currentEntry;session.interactionEvents.push({type:prepared.reason==="refocus_future"?"visit_refocus_requested":"visit_extension_requested",contentEntryId:current._id,variantKey:current.variantKey||null,metadata:prepared.reason==="refocus_future"?{museumId:prepared.museumId,semanticGoals:payload.semanticGoals||[],relationGoals:payload.relationGoals||[]}:{additionalTimeSeconds:Number(payload.additionalTimeSeconds)||null},at:new Date()});await session.save()}if(payload.remember===true)await rememberGenerationPreferences({userId,payload});return proposal}
async function markProposalStale(proposal){proposal.status="stale";proposal.resolvedAt=new Date();await proposal.save();}
async function compensateActivation({session,proposal,revision,baseSuperseded}){const rollback={currentPlanRevisionId:proposal.basePlanRevisionId,currentEntryIndex:proposal.currentEntryIndex};if(session.status==="route_completed"&&proposal.reason==="extend_visit"){rollback.status="route_completed";rollback.routeCompletedAt=session.routeCompletedAt||new Date()}const pointer=await VisitSession.updateOne({_id:session._id,currentPlanRevisionId:revision._id},{$set:rollback});let baseRollback={modifiedCount:1};if(baseSuperseded)baseRollback=await SessionPlanRevision.updateOne({_id:proposal.basePlanRevisionId,status:"superseded"},{$set:{status:"active"}});await SessionPlanRevision.deleteOne({_id:revision._id,sessionId:session._id}).catch(()=>{});if(pointer.modifiedCount!==1||baseRollback.modifiedCount!==1)throw new AppError("Attivazione piano fallita con rollback incompleto",500,[{code:"SESSION_PLAN_ACTIVATION_ROLLBACK_FAILED"}])}
async function resolvePlanChangeProposal({userId,proposalId,accept}){const proposal=await Proposal.findOne({_id:proposalId,userId});if(!proposal)throw new AppError("Proposta non trovata",404);if(proposal.status!=="pending")throw new AppError("Proposta gia risolta",409);const session=await VisitSession.findOne({_id:proposal.sessionId,userId});if(!session)throw new AppError("Sessione non trovata",404);if(id(session.currentPlanRevisionId)!==id(proposal.basePlanRevisionId)){await markProposalStale(proposal);throw new AppError("Proposta obsoleta",409)}if(!accept){proposal.status="rejected";proposal.resolvedAt=new Date();await proposal.save();return{proposal,session}}const version=await nextPlanVersion(session._id);const revision=await SessionPlanRevision.create({sessionId:session._id,version,basedOnRevisionId:proposal.basePlanRevisionId,status:"active",...H.plain(proposal.proposedRevision)});let switched=false,baseSuperseded=false;try{const sessionSet={currentPlanRevisionId:revision._id,currentEntryIndex:proposal.currentEntryIndex};if(session.status==="route_completed"&&proposal.reason==="extend_visit"){sessionSet.status="active";sessionSet.routeCompletedAt=null}const pointer=await VisitSession.updateOne({_id:session._id,userId,currentPlanRevisionId:proposal.basePlanRevisionId},{$set:sessionSet});if(pointer.modifiedCount!==1){await SessionPlanRevision.deleteOne({_id:revision._id}).catch(()=>{});await markProposalStale(proposal);throw new AppError("Proposta obsoleta",409)}switched=true;const supersede=await SessionPlanRevision.updateOne({_id:proposal.basePlanRevisionId,sessionId:session._id,status:"active"},{$set:{status:"superseded"}});if(supersede.modifiedCount!==1)throw new Error("Impossibile supersedere il piano base");baseSuperseded=true;const resolved=await Proposal.updateOne({_id:proposal._id,status:"pending",basePlanRevisionId:proposal.basePlanRevisionId},{$set:{status:"accepted",resolvedAt:new Date()}});if(resolved.modifiedCount!==1)throw new Error("Impossibile finalizzare la proposta")}catch(error){if(switched)await compensateActivation({session,proposal,revision,baseSuperseded});else await SessionPlanRevision.deleteOne({_id:revision._id}).catch(()=>{});if(error instanceof AppError)throw error;throw new AppError("Impossibile attivare atomicamente il nuovo piano di sessione",500,[{code:"SESSION_PLAN_ACTIVATION_FAILED",message:error.message}])}await Proposal.updateMany({sessionId:session._id,status:"pending",_id:{$ne:proposal._id}},{$set:{status:"stale",resolvedAt:new Date()}}).catch(()=>{});const[resolvedProposal,updatedSession]=await Promise.all([Proposal.findById(proposal._id),VisitSession.findById(session._id)]);return{proposal:resolvedProposal,session:updatedSession,planRevision:revision}}
module.exports={FIDELITIES:R.FIDELITIES,REASONS:R.REASONS,mergeSemanticGoals:H.mergeSemanticGoals,mergeRelationGoals:H.mergeRelationGoals,remainingSeconds:H.remainingSeconds,segmentEndForMuseum:H.segmentEndForMuseum,canonicalEntryIndex,proposePlanChange,resolvePlanChangeProposal,rememberGenerationPreferences};
