const AppError=require("../utils/AppError");
const policy=require("../config/adaptivePolicy");
const H=require("./planAdaptation.helpers");
const{anchorMap}=require("./physicalRoute.service");
const{id}=require("./sessionPlan.service");
const FIDELITIES=["preserve","adapt","regenerate"];
const REASONS=["ahead_of_schedule","behind_schedule","manual_request","refocus_future","extend_visit","parameter_change","route_only"];
const SCALARS=["movementPacePreference","depthPreference","languageComplexityPreference","observationEmphasis","visitDensity","discoveryPreference","timeRiskTolerance"];
function reasonFor(payload,session,ratio){if(payload.reason!==undefined){if(!REASONS.includes(payload.reason))throw new AppError("reason non valido",400);return payload.reason}if(session.status==="route_completed")return"extend_visit";if(ratio>=1+policy.generator.replanTriggerRatio)return"ahead_of_schedule";if(ratio<=1-policy.generator.replanTriggerRatio)return"behind_schedule";return"manual_request"}
function fidelityFor(plan,reason,requested){if(requested!==undefined&&!FIDELITIES.includes(requested))throw new AppError("fidelity non valida",400);if(requested)return requested;if(plan.origin?.sourceType!=="visit")return"adapt";return["behind_schedule","refocus_future","parameter_change","extend_visit"].includes(reason)?"adapt":"preserve"}
function messageKey(reason){if(reason==="ahead_of_schedule")return"SUGGEST_EXTEND_VISIT";if(reason==="behind_schedule")return"SUGGEST_SHORTEN_VISIT";if(reason==="refocus_future")return"SUGGEST_REFOCUS_VISIT";if(reason==="extend_visit")return"SUGGEST_CONTINUE_VISIT";if(reason==="route_only")return"SUGGEST_ROUTE_UPDATE";return"SUGGEST_ADAPT_VISIT"}
function requestedBudget(payload,session,currentRemaining,reason){let value=Number(payload.remainingTimeBudgetSeconds);if(!Number.isFinite(value)||value<=0)value=currentRemaining;const additional=Number(payload.additionalTimeSeconds);if(Number.isFinite(additional)&&additional>0)value=reason==="extend_visit"&&session.status==="route_completed"?additional:value+additional;if(reason==="extend_visit"&&session.status==="route_completed"&&value===currentRemaining&&(!Number.isFinite(additional)||additional<=0))throw new AppError("Per estendere la visita indicare il tempo aggiuntivo",400);return value}
function prepareAdaptation({plan,session,payload,currentEntryIndex,elapsed}){
 const currentEntry=plan.contentEntries[currentEntryIndex],originalBudget=Number(plan.requestSnapshot?.timeBudgetSeconds)||Number(plan.estimatedTiming?.totalSeconds)||1;
 const currentRemaining=Math.max(1,originalBudget-elapsed),originalRemaining=H.remainingSeconds(plan,currentEntryIndex),ratio=originalRemaining>0?currentRemaining/originalRemaining:1,reason=reasonFor(payload,session,ratio),fidelity=fidelityFor(plan,reason,payload.fidelity),remainingBudget=requestedBudget(payload,session,currentRemaining,reason);
 const segmentEnd=H.segmentEndForMuseum(plan.contentEntries,plan.physicalRoute,currentEntryIndex),museumId=H.physicalMuseumForEntry(plan,currentEntry),futureSegment=plan.contentEntries.slice(currentEntryIndex+1,segmentEnd+1),suffixEntries=plan.contentEntries.slice(segmentEnd+1).map(H.plain),pieces=H.routePieces(plan,currentEntryIndex,segmentEnd),currentAnchor=anchorMap(plan.physicalRoute).get(id(currentEntry.deliveryAnchorId));
 const suffixTiming=suffixEntries.reduce((s,e)=>s+(Number(e.estimatedContentSeconds)||0),0)+pieces.suffixAnchors.reduce((s,a)=>s+(Number(a.estimatedObservationSeconds)||0),0)+[...(pieces.boundaryLeg?[pieces.boundaryLeg]:[]),...pieces.suffixLegs].reduce((s,l)=>s+(Number(l.estimatedSeconds)||0),0);if(suffixEntries.length&&suffixTiming>=remainingBudget)throw new AppError("Il tempo indicato non basta per la parte multi-museo bloccata",409);
 const generationBudget=Math.max(1,remainingBudget-suffixTiming),visitedIds=new Set(plan.contentEntries.slice(0,currentEntryIndex+1).map(e=>id(e.itemId))),constraints=H.fidelityConstraints({plan,futureSegment,fidelity,visitedIds,payload}),stability=H.stabilityGoals(futureSegment,fidelity,constraints.include);
 const request={...H.plain(plan.requestSnapshot||{}),timeBudgetSeconds:generationBudget,startPlaceId:payload.currentPlaceId||currentAnchor?.placeId||null,endPlaceId:suffixEntries.length?null:(payload.endPlaceId??plan.requestSnapshot?.endPlaceId??null),hardTimeBudget:payload.hardTimeBudget===undefined?true:payload.hardTimeBudget!==false,semanticGoals:H.mergeSemanticGoals(plan.requestSnapshot?.semanticGoals||[],[...(payload.semanticGoals||[]),...stability],payload.replaceSemanticGoals===true),relationGoals:H.mergeRelationGoals(plan.requestSnapshot?.relationGoals||[],payload.relationGoals||[],payload.replaceRelationGoals===true),mustIncludeItemIds:constraints.include,mustVisitItemIds:constraints.visit,spatialConstraints:constraints.spatialConstraints,excludedItemIds:[...new Set([...(plan.requestSnapshot?.excludedItemIds||[]).map(id),...(payload.excludedItemIds||[]).map(id),...visitedIds])]};
 for(const field of SCALARS)if(payload[field]!==undefined)request[field]=payload[field];for(const field of["coverageGoal","historyMode","audience","knowledge"])if(payload[field]!==undefined)request[field]=payload[field];if(Array.isArray(payload.navigationRequirements))request.navigationRequirements=payload.navigationRequirements;
 const plannerConstraints=fidelity==="preserve"?{fixedOrderItemIds:futureSegment.map(entry=>entry.itemId)}:{};
 return{currentEntry,reason,fidelity,currentRemaining,originalRemaining,ratio,remainingBudget,segmentEnd,museumId,futureSegment,suffixEntries,pieces,currentAnchor,constraints,request,plannerConstraints};
}
module.exports={FIDELITIES,REASONS,SCALARS,messageKey,prepareAdaptation};
