const policy = require("../config/adaptivePolicy");
const { id } = require("./sessionPlan.service");
const { anchorMap } = require("./physicalRoute.service");
function plain(value) { return value?.toObject ? value.toObject() : { ...value }; }
function featureIdentity(feature) { if (!feature) return ""; if (feature.kind === "item") return `item:${id(feature.itemId)}`; if (feature.kind === "canonical") return `canonical:${String(feature.scheme || "").toLowerCase()}:${feature.id || feature.refId || ""}`; return `${feature.kind || ""}:${String(feature.key || "").toLowerCase()}`; }
function semanticGoalIdentity(goal) { return goal?.feature ? `${goal.priority || "preferred"}:${featureIdentity(goal.feature)}` : ""; }
function relationGoalIdentity(goal) { if (!goal?.kind) return ""; return [goal.kind, goal.priority || "preferred", featureIdentity(goal.from), featureIdentity(goal.to), goal.relationTypeKey || ""].join("|"); }
function mergeByIdentity(base = [], additions = [], replace = false, identity) { const map = new Map(); if (!replace) for (const value of base || []) { const key = identity(value); if (key) map.set(key, value); } for (const value of additions || []) { const key = identity(value); if (key) map.set(key, value); } return [...map.values()]; }
function mergeSemanticGoals(base = [], additions = [], replace = false) { return mergeByIdentity(base, additions, replace, semanticGoalIdentity); }
function mergeRelationGoals(base = [], additions = [], replace = false) { return mergeByIdentity(base, additions, replace, relationGoalIdentity); }
function uniqueIds(values = []) { return [...new Map(values.filter(Boolean).map((value) => [id(value), value])).values()]; }
function entryIndexMap(entries = []) { return new Map(entries.map((entry, index) => [id(entry._id), index])); }
function physicalMuseumForEntry(plan, entry) { const anchor = anchorMap(plan.physicalRoute).get(id(entry?.deliveryAnchorId)); return id(anchor?.museumId || entry?.museumId); }
function remainingSeconds(plan, currentEntryIndex) { const indexes = entryIndexMap(plan.contentEntries || []); const content = (plan.contentEntries || []).slice(currentEntryIndex + 1).reduce((sum, entry) => sum + (Number(entry.estimatedContentSeconds) || 0), 0); const observation = (plan.physicalRoute?.anchors || []).filter((anchor) => anchor.contentEntryId && (indexes.get(id(anchor.contentEntryId)) ?? -1) > currentEntryIndex).reduce((sum, anchor) => sum + (Number(anchor.estimatedObservationSeconds) || 0), 0); const anchors = anchorMap(plan.physicalRoute); const logistics = (plan.physicalRoute?.legs || []).filter((leg) => { const target = anchors.get(id(leg.toAnchorId)); if (target?.contentEntryId) return (indexes.get(id(target.contentEntryId)) ?? -1) > currentEntryIndex; return target?.purpose === "end"; }).reduce((sum, leg) => sum + (Number(leg.estimatedSeconds) || 0), 0); return content + observation + logistics; }
function segmentEndForMuseum(entries, physicalRoute, currentEntryIndex) { const plan = { contentEntries: entries, physicalRoute }, museumId = physicalMuseumForEntry(plan, entries[currentEntryIndex]); let end = currentEntryIndex; for (let index = currentEntryIndex + 1; index < entries.length; index += 1) { if (physicalMuseumForEntry(plan, entries[index]) !== museumId) break; end = index; } return end; }
function routePieces(plan, currentEntryIndex, segmentEnd) { const indexes = entryIndexMap(plan.contentEntries || []), anchors = plan.physicalRoute?.anchors || [], legs = plan.physicalRoute?.legs || [], currentEntry = plan.contentEntries[currentEntryIndex], currentAnchorId = id(currentEntry?.deliveryAnchorId); const prefixIds = new Set(anchors.filter((anchor) => anchor.purpose === "start" || (anchor.contentEntryId && (indexes.get(id(anchor.contentEntryId)) ?? Infinity) <= currentEntryIndex)).map((anchor) => id(anchor._id))); if (currentAnchorId) prefixIds.add(currentAnchorId); const prefixAnchors = anchors.filter((anchor) => prefixIds.has(id(anchor._id))).map(plain), prefixLegs = legs.filter((leg) => prefixIds.has(id(leg.fromAnchorId)) && prefixIds.has(id(leg.toAnchorId))).map(plain); const suffixEntryIds = new Set((plan.contentEntries || []).slice(segmentEnd + 1).map((entry) => id(entry._id))), suffixAnchors = anchors.filter((anchor) => anchor.contentEntryId && suffixEntryIds.has(id(anchor.contentEntryId))).map(plain), suffixIds = new Set(suffixAnchors.map((anchor) => id(anchor._id))); const endAnchors = anchors.filter((anchor) => anchor.purpose === "end" && legs.some((leg) => suffixIds.has(id(leg.fromAnchorId)) && id(leg.toAnchorId) === id(anchor._id))).map(plain); endAnchors.forEach((anchor) => suffixIds.add(id(anchor._id))); const suffixLegs = legs.filter((leg) => suffixIds.has(id(leg.fromAnchorId)) && suffixIds.has(id(leg.toAnchorId))).map(plain), firstSuffixAnchor = suffixAnchors[0] || null, boundaryLeg = firstSuffixAnchor ? legs.find((leg) => id(leg.toAnchorId) === id(firstSuffixAnchor._id) && !suffixIds.has(id(leg.fromAnchorId))) : null; return { currentAnchorId, prefixAnchors, prefixLegs, suffixAnchors: [...suffixAnchors, ...endAnchors], suffixLegs, firstSuffixAnchor, boundaryLeg: boundaryLeg ? plain(boundaryLeg) : null }; }
function normalizeTailStart(tailEntries, tailRoute, currentAnchorId) { const anchors = (tailRoute?.anchors || []).map(plain), legs = (tailRoute?.legs || []).map(plain), entries = tailEntries.map(plain), start = anchors.find((anchor) => anchor.purpose === "start"); if (!start || !currentAnchorId) return { entries, anchors, legs, lastAnchorId: anchors.at(-1)?._id || currentAnchorId }; for (const entry of entries) if (id(entry.deliveryAnchorId) === id(start._id)) entry.deliveryAnchorId = currentAnchorId; for (const leg of legs) if (id(leg.fromAnchorId) === id(start._id)) leg.fromAnchorId = currentAnchorId; const kept = anchors.filter((anchor) => id(anchor._id) !== id(start._id)); return { entries, anchors: kept, legs, lastAnchorId: kept.at(-1)?._id || currentAnchorId }; }
function mergeRoute({ prefix, tail, suffix, boundary }) { const anchors = [...prefix.anchors, ...tail.anchors, ...suffix.anchors], legs = [...prefix.legs, ...tail.legs]; if (suffix.anchors.length && boundary) legs.push({ ...boundary, fromAnchorId: tail.lastAnchorId || prefix.currentAnchorId, toAnchorId: suffix.anchors[0]._id }); legs.push(...suffix.legs); return { anchors, legs }; }
function fidelityConstraints({ plan, futureSegment, fidelity, visitedIds, payload }) { const existingInclude = (plan.requestSnapshot?.mustIncludeItemIds || []).filter((itemId) => !visitedIds.has(id(itemId))), existingVisit = (plan.requestSnapshot?.mustVisitItemIds || []).filter((itemId) => !visitedIds.has(id(itemId))), fidelityEntries = fidelity === "preserve" ? futureSegment : fidelity === "adapt" ? futureSegment.filter((entry) => entry.role === "core") : []; const include = uniqueIds([...existingInclude, ...fidelityEntries.map((entry) => entry.itemId), ...(payload.addMustIncludeItemIds || [])]).filter((value) => !(payload.removeMustIncludeItemIds || []).some((removed) => id(removed) === id(value))); const visit = uniqueIds([...existingVisit, ...fidelityEntries.filter((entry) => entry.spatialMode === "target").map((entry) => entry.itemId), ...(payload.addMustVisitItemIds || [])]).filter((value) => !(payload.removeMustVisitItemIds || []).some((removed) => id(removed) === id(value))); const byItem = new Map(); for (const entry of fidelityEntries) byItem.set(id(entry.itemId), { itemId: entry.itemId, spatialMode: entry.spatialMode }); for (const constraint of payload.spatialConstraints || []) byItem.set(id(constraint.itemId), constraint); return { include, visit, spatialConstraints: [...byItem.values()] }; }
function stabilityGoals(futureSegment, fidelity, mustInclude) { if (fidelity === "regenerate") return []; const must = new Set(mustInclude.map(id)); return futureSegment.filter((entry) => !must.has(id(entry.itemId))).map((entry) => ({ priority: "preferred", feature: { kind: "item", itemId: entry.itemId }, weight: fidelity === "preserve" ? 0.8 : policy.generator.stabilityPenalty })); }
module.exports = { plain, featureIdentity, semanticGoalIdentity, relationGoalIdentity, mergeSemanticGoals, mergeRelationGoals, uniqueIds, physicalMuseumForEntry, remainingSeconds, segmentEndForMuseum, routePieces, normalizeTailStart, mergeRoute, fidelityConstraints, stabilityGoals };
