const VisitSession=require("../models/visitSession.model");
const SessionPlanRevision=require("../models/sessionPlanRevision.model");
const Proposal=require("../models/plan_change_proposal.model");
const UserGenerationPreference=require("../models/userGenerationPreference.model");
const AppError=require("../utils/AppError");
const{activeElapsedSeconds}=require("./visitSession.service");
const{getCurrentSessionPlan,nextPlanVersion,id}=require("./sessionPlan.service");
const H=require("./planAdaptation.helpers"),R=require("./planAdaptation.request"),C=require("./planAdaptation.compose");
async function rememberGenerationPreferences({userId,payload}){const set={};for(const field of[...R.SCALARS,"semanticGoals","relationGoals","coverageGoal","audience","knowledge","navigationRequirements"])if(payload[field]!==undefined)set[field]=payload[field];if(!Object.keys(set).length)return null;return UserGenerationPreference.findOneAndUpdate({userId},{$set:set},{upsert:true,new:true,runValidators:true,setDefaultsOnInsert:true})}
async function proposePlanChange({userId,sessionId,payload={}}){const{session,plan}=await getCurrentSessionPlan({sessionId,userId});if(session.status==="paused"&&!["manual_request","refocus_future","parameter_change","route_only"].includes(payload.reason))throw new AppError("Riprendere la visita prima del replanning automatico",409);const max=Math.max(0,(plan.contentEntries||[]).length-1),asked=Number(payload.currentEntryIndex),index=session.status==="route_completed"?max:Math.min(max,Number.isInteger(asked)?Math.max(0,asked):session.currentEntryIndex||0);if(!plan.contentEntries?.[index])throw new AppError("Contenuto corrente non disponibile",409);const elapsed=activeElapsedSeconds(session),prepared=R.prepareAdaptation({plan,session,payload,currentEntryIndex:index,elapsed}),tail=await C.buildTail({userId,plan,prepared}),composed=C.composeRevision({plan,prepared,tail,currentEntryIndex:index,elapsed});const proposal=await Proposal.create({userId,sessionId:session._id,basePlanRevisionId:plan._id,reason:prepared.reason,fidelity:prepared.fidelity,currentEntryIndex:index,adaptationRequest:payload,currentEstimate:{activeElapsedSeconds:Math.round(elapsed),remainingBudgetSeconds:Math.round(prepared.currentRemaining),requestedRemainingBudgetSeconds:Math.round(prepared.remainingBudget),proposedTotalSessionBudgetSeconds:composed.totalSessionBudgetSeconds,currentPlanRemainingSeconds:Math.round(prepared.originalRemaining),deviationRatio:prepared.ratio},proposedRevision:composed.revision,messageKey:R.messageKey(prepared.reason)});if(["refocus_future","extend_visit"].includes(prepared.reason)){const current=prepared.currentEntry;session.interactionEvents.push({type:prepared.reason==="refocus_future"?"visit_refocus_requested":"visit_extension_requested",contentEntryId:current._id,variantKey:current.variantKey||null,metadata:prepared.reason==="refocus_future"?{museumId:prepared.museumId,semanticGoals:payload.semanticGoals||[],relationGoals:payload.relationGoals||[]}:{additionalTimeSeconds:Number(payload.additionalTimeSeconds)||null},at:new Date()});await session.save()}if(payload.remember===true)await rememberGenerationPreferences({userId,payload});return proposal}
async function resolvePlanChangeProposal({userId,proposalId,accept}){const proposal=await Proposal.findOne({_id:proposalId,userId});if(!proposal)throw new AppError("Proposta non trovata",404);if(proposal.status!=="pending")throw new AppError("Proposta gia risolta",409);const session=await VisitSession.findOne({_id:proposal.sessionId,userId});if(!session)throw new AppError("Sessione non trovata",404);if(id(session.currentPlanRevisionId)!==id(proposal.basePlanRevisionId)){proposal.status="stale";proposal.resolvedAt=new Date();await proposal.save();throw new AppError("Proposta obsoleta",409)}if(!accept){proposal.status="rejected";proposal.resolvedAt=new Date();await proposal.save();return{proposal,session}}const version=await nextPlanVersion(session._id),revision=await SessionPlanRevision.create({sessionId:session._id,version,basedOnRevisionId:proposal.basePlanRevisionId,status:"active",...H.plain(proposal.proposedRevision)});await SessionPlanRevision.updateOne({_id:proposal.basePlanRevisionId},{$set:{status:"superseded"}});session.currentPlanRevisionId=revision._id;session.currentEntryIndex=proposal.currentEntryIndex;if(session.status==="route_completed"&&proposal.reason==="extend_visit"){session.status="active";session.routeCompletedAt=null}await session.save();proposal.status="accepted";proposal.resolvedAt=new Date();await proposal.save();await Proposal.updateMany({sessionId:session._id,status:"pending",_id:{$ne:proposal._id}},{$set:{status:"stale",resolvedAt:new Date()}});return{proposal,session,planRevision:revision}}
module.exports={FIDELITIES:R.FIDELITIES,REASONS:R.REASONS,mergeSemanticGoals:H.mergeSemanticGoals,mergeRelationGoals:H.mergeRelationGoals,remainingSeconds:H.remainingSeconds,segmentEndForMuseum:H.segmentEndForMuseum,proposePlanChange,resolvePlanChangeProposal,rememberGenerationPreferences};
