const AppError = require("../utils/AppError");
const policy = require("../config/adaptivePolicy");
const { resolveRoute } = require("./graphRouting.service");
const { id, relationCoherence, pruneBeam, compareStates } = require("./visitGeneratorSemantics.service");
const { newObjectId } = require("./physicalRoute.service");

function optimizeVisit({ options, context, layoutRevision, requirements = [], learnedResidualByConnection = new Map(), startPlaceId = null, graph = null, requiredSemanticKeys = [] }) {
  const mustInclude = new Set((context.mustIncludeItemIds || []).map(id)), mustVisit = new Set((context.mustVisitItemIds || []).map(id));
  const includeAvailable = new Set(options.map((option) => id(option.item._id))), visitAvailable = new Set(options.filter((option) => option.spatialMode === "target").map((option) => id(option.item._id)));
  const missingInclude = [...mustInclude].filter((itemId) => !includeAvailable.has(itemId)), missingVisit = [...mustVisit].filter((itemId) => !visitAvailable.has(itemId));
  if (missingInclude.length || missingVisit.length) throw new AppError("Alcuni vincoli di inclusione non sono soddisfacibili", 409, [...missingInclude.map((itemId) => ({ field: "mustIncludeItemIds", code: "MUST_INCLUDE_UNAVAILABLE", message: `Item non includibile: ${itemId}` })), ...missingVisit.map((itemId) => ({ field: "mustVisitItemIds", code: "MUST_VISIT_UNAVAILABLE", message: `Item non visitabile fisicamente: ${itemId}` }))]);
  const hardKeys = [...mustInclude].map((itemId) => `include:${itemId}`).concat([...mustVisit].map((itemId) => `visit:${itemId}`), requiredSemanticKeys || []), requiredCount = hardKeys.length, hardKeySet = new Set(hardKeys), routeCache = new Map();
  function routeBetween(fromPlaceId, toPlaceId) { if (!fromPlaceId) return { reachable: true, path: [], estimatedSeconds: 0, preferencePenalty: 0 }; if (!layoutRevision) return { reachable: false }; const key = `${id(fromPlaceId)}>${id(toPlaceId)}`; if (!routeCache.has(key)) routeCache.set(key, resolveRoute({ connections: layoutRevision.connections, fromPlaceId, toPlaceId, requirements, speedMps: context.effectiveMovementSpeedMps, learnedResidualByConnection })); return routeCache.get(key); }
  const reserveRatio = policy.generator.conservativeTimeReserveRatio * (1 - context.dimensions.timeRisk.value), reservedSeconds = Math.round(context.timeBudgetSeconds * reserveRatio), usableBudget = Math.max(1, context.timeBudgetSeconds - reservedSeconds);
  function optionHardKeys(option) { const itemId = id(option.item._id), keys = []; if (mustInclude.has(itemId)) keys.push(`include:${itemId}`); if (option.spatialMode === "target" && mustVisit.has(itemId)) keys.push(`visit:${itemId}`); for (const key of option.requiredCoverageKeys || []) if (hardKeySet.has(key)) keys.push(key); return [...new Set(keys)]; }
  function emptyState() { const startAnchor = startPlaceId ? { _id: newObjectId(), kind: "place", purpose: "start", contentEntryId: null, itemId: null, museumId: context.museumId, placeId: startPlaceId, estimatedObservationSeconds: 0 } : null; return { selectedItemIds: new Set(), hardCoverage: new Set(), hardCovered: 0, currentPlaceId: startPlaceId, currentAnchorId: startAnchor?._id || null, entries: [], anchors: startAnchor ? [startAnchor] : [], legs: [], elapsedSeconds: 0, contentSeconds: 0, observationSeconds: 0, logisticsSeconds: 0, explicitScore: 0, utility: 0, itemTypeCounts: new Map(), preferenceCoverageCounts: new Map(), lastOption: null }; }
  function preferenceGain(state, option) { const matches = option.preferenceMatches?.length ? option.preferenceMatches : (option.explicitPreference > 0 ? [{ key: "current-request", score: option.explicitPreference }] : []); if (!matches.length) return 0; return matches.reduce((sum, match) => sum + (Number(match.score) || 0) / (1 + (state.preferenceCoverageCounts.get(match.key) || 0)), 0) / matches.length; }
  function nonExplicitGain(state, option, routeSeconds) { const sameTypeCount = state.itemTypeCounts.get(option.item.itemType) || 0, diversityPenalty = Math.max(0, sameTypeCount - 1) * 0.18, coherence = relationCoherence(state.lastOption, option, graph), logisticsPenalty = (routeSeconds / Math.max(usableBudget, 1)) * policy.generator.logisticsUtilityWeight; return (Number(option.nonExplicitUtility) || 0) + coherence - diversityPenalty - logisticsPenalty; }
  function appendOption(state, option) {
    if (state.selectedItemIds.has(id(option.item._id))) return null;
    let route = { reachable: true, path: [], estimatedSeconds: 0, preferencePenalty: 0 };
    if (option.spatialMode === "target") { if (!option.placement?.primaryPlaceId) return null; route = routeBetween(state.currentPlaceId, option.placement.primaryPlaceId); if (!route.reachable) return null; }
    const observation = option.spatialMode === "target" ? Number(option.observationSeconds) || 0 : 0, nextElapsed = state.elapsedSeconds + (Number(option.targetSeconds) || 0) + observation + route.estimatedSeconds; if (context.hardTimeBudget && nextElapsed > usableBudget) return null;
    const entryId = newObjectId(); let deliveryAnchorId = state.currentAnchorId, currentPlaceId = state.currentPlaceId, currentAnchorId = state.currentAnchorId; const anchors = [...state.anchors], legs = [...state.legs];
    if (option.spatialMode === "target") { const anchor = { _id: newObjectId(), kind: "content_target", purpose: "content", contentEntryId: entryId, itemId: option.item._id, museumId: context.museumId, placeId: option.placement.primaryPlaceId, estimatedObservationSeconds: Math.round(observation) }; if (state.currentAnchorId) legs.push({ _id: newObjectId(), type: "indoor", fromAnchorId: state.currentAnchorId, toAnchorId: anchor._id, layoutRevisionId: layoutRevision?._id || null, path: (route.path || []).map((entry) => entry.connectionId || entry), estimatedSeconds: Math.round(route.estimatedSeconds), preferencePenalty: route.preferencePenalty || 0, instruction: null, communityNote: null }); anchors.push(anchor); deliveryAnchorId = anchor._id; currentPlaceId = anchor.placeId; currentAnchorId = anchor._id; }
    const selected = new Set(state.selectedItemIds); selected.add(id(option.item._id)); const hardCoverage = new Set(state.hardCoverage); for (const key of optionHardKeys(option)) hardCoverage.add(key); const counts = new Map(state.itemTypeCounts); counts.set(option.item.itemType, (counts.get(option.item.itemType) || 0) + 1); const preferenceCoverageCounts = new Map(state.preferenceCoverageCounts); for (const match of option.preferenceMatches || []) if ((Number(match.score) || 0) > 0) preferenceCoverageCounts.set(match.key, (preferenceCoverageCounts.get(match.key) || 0) + 1);
    return { selectedItemIds: selected, hardCoverage, hardCovered: hardCoverage.size, currentPlaceId, currentAnchorId, entries: [...state.entries, { _id: entryId, option, deliveryAnchorId }], anchors, legs, elapsedSeconds: nextElapsed, contentSeconds: state.contentSeconds + option.targetSeconds, observationSeconds: state.observationSeconds + observation, logisticsSeconds: state.logisticsSeconds + route.estimatedSeconds, explicitScore: state.explicitScore + preferenceGain(state, option), utility: state.utility + nonExplicitGain(state, option, route.estimatedSeconds), itemTypeCounts: counts, preferenceCoverageCounts, lastOption: option };
  }
  function finalize(state) { if (!context.endPlaceId) return state; const route = routeBetween(state.currentPlaceId, context.endPlaceId); if (!route.reachable) return null; const elapsedSeconds = state.elapsedSeconds + route.estimatedSeconds; if (context.hardTimeBudget && elapsedSeconds > usableBudget) return null; const end = { _id: newObjectId(), kind: "place", purpose: "end", contentEntryId: null, itemId: null, museumId: context.museumId, placeId: context.endPlaceId, estimatedObservationSeconds: 0 }, legs = [...state.legs]; if (state.currentAnchorId) legs.push({ _id: newObjectId(), type: "indoor", fromAnchorId: state.currentAnchorId, toAnchorId: end._id, layoutRevisionId: layoutRevision?._id || null, path: (route.path || []).map((entry) => entry.connectionId || entry), estimatedSeconds: Math.round(route.estimatedSeconds), preferencePenalty: route.preferencePenalty || 0, instruction: null, communityNote: null }); return { ...state, currentPlaceId: context.endPlaceId, currentAnchorId: end._id, anchors: [...state.anchors, end], legs, elapsedSeconds, logisticsSeconds: state.logisticsSeconds + route.estimatedSeconds, utility: state.utility - (route.estimatedSeconds / Math.max(usableBudget, 1)) * policy.generator.logisticsUtilityWeight }; }
  function evaluateOrder(orderedOptions) { let state = emptyState(); for (const option of orderedOptions) { state = appendOption(state, option); if (!state) return null; } if (state.hardCovered !== requiredCount) return null; return finalize(state); }

  let beam = [emptyState()]; const uniqueItemCount = new Set(options.map((option) => id(option.item._id))).size, maxEntries = context.coverageGoal === "all" ? uniqueItemCount : Math.min(policy.generator.maxContentEntries, Math.max(1, uniqueItemCount));
  for (let depth = 0; depth < maxEntries; depth += 1) {
    const expanded = [...beam];
    for (const state of beam) {
      const remaining = options.filter((option) => !state.selectedItemIds.has(id(option.item._id))).sort((a, b) => optionHardKeys(b).filter((key) => !state.hardCoverage.has(key)).length - optionHardKeys(a).filter((key) => !state.hardCoverage.has(key)).length || b.explicitPreference - a.explicitPreference || b.baseUtility - a.baseUtility).slice(0, policy.generator.branchCandidates + requiredCount);
      for (const option of remaining) { const next = appendOption(state, option); if (next) expanded.push(next); }
    }
    const nextBeam = pruneBeam(expanded, requiredCount, policy.generator.beamWidth); if (nextBeam.every((state) => state.entries.length <= depth)) break; beam = nextBeam;
  }
  let finals = beam.filter((state) => state.entries.length > 0 && state.hardCovered === requiredCount).map(finalize).filter(Boolean); finals.sort((a, b) => compareStates(a, b, requiredCount)); let best = finals[0], usedFeasibilityFallback = false;

  if (!best && requiredCount) {
    const bitByKey = new Map(hardKeys.map((key, index) => [key, 1n << BigInt(index)])), fullMask = hardKeys.reduce((mask, key) => mask | bitByKey.get(key), 0n), relevant = options.map((option) => ({ option, mask: optionHardKeys(option).reduce((mask, key) => mask | (bitByKey.get(key) || 0n), 0n) })).filter((entry) => entry.mask !== 0n);
    const start = { mask: 0n, currentPlaceId: startPlaceId, elapsed: 0, sequence: [], selected: new Set() }, queue = [start], bestByState = new Map([[`0|${id(startPlaceId)}`, 0]]); let feasible = null;
    while (queue.length) {
      queue.sort((a, b) => a.elapsed - b.elapsed); const state = queue.shift(); if (state.mask === fullMask) { const evaluated = evaluateOrder(state.sequence); if (evaluated) { feasible = evaluated; break; } }
      for (const entry of relevant) {
        const itemId = id(entry.option.item._id); if (state.selected.has(itemId)) continue; const nextMask = state.mask | entry.mask; if (nextMask === state.mask) continue;
        let routeSeconds = 0, nextPlace = state.currentPlaceId; if (entry.option.spatialMode === "target") { const route = routeBetween(state.currentPlaceId, entry.option.placement?.primaryPlaceId); if (!route.reachable) continue; routeSeconds = route.estimatedSeconds; nextPlace = entry.option.placement.primaryPlaceId; }
        const elapsed = state.elapsed + Number(entry.option.targetSeconds || 0) + (entry.option.spatialMode === "target" ? Number(entry.option.observationSeconds || 0) : 0) + routeSeconds; if (context.hardTimeBudget && elapsed > usableBudget) continue;
        const key = `${nextMask.toString()}|${id(nextPlace)}`; if ((bestByState.get(key) ?? Infinity) <= elapsed) continue; bestByState.set(key, elapsed); const selected = new Set(state.selected); selected.add(itemId); queue.push({ mask: nextMask, currentPlaceId: nextPlace, elapsed, sequence: [...state.sequence, entry.option], selected });
      }
    }
    if (feasible) { best = feasible; usedFeasibilityFallback = true; }
  }
  if (!best) throw new AppError("I vincoli richiesti non sono compatibili con il tempo o i dati disponibili", 409, [{ field: "timeBudgetSeconds", code: "GENERATION_CONSTRAINT_CONFLICT", message: "Nessun piano fattibile soddisfa tutti i vincoli hard" }]);

  function blockOrder(entries) { const intro = [], groups = []; let current = null; for (const entry of entries) { const option = entry.option; if (option.spatialMode === "target") { current = [option]; groups.push(current); } else if (current) current.push(option); else intro.push(option); } return { intro, groups }; }
  for (let pass = 0; pass < policy.generator.localImprovementPasses; pass += 1) { const { intro, groups } = blockOrder(best.entries); let improved = best; for (let left = 0; left < groups.length - 1; left += 1) for (let right = left + 1; right < groups.length; right += 1) { const reorderedGroups = [...groups.slice(0, left), ...groups.slice(left, right + 1).reverse(), ...groups.slice(right + 1)], candidate = evaluateOrder([...intro, ...reorderedGroups.flat()]); if (candidate && compareStates(candidate, improved, requiredCount) < 0) improved = candidate; } if (improved === best) break; best = improved; }
  return { best, reservedSeconds, searchDiagnostics: { beamFoundFeasible: finals.length > 0, usedFeasibilityFallback, hardRequirementCount: requiredCount } };
}
module.exports = { optimizeVisit };
