const mongoose = require("mongoose");
const IntegrityIssueSchema = require("../schemas/integrityIssue.schema");
const SemanticRefSchema = require("../schemas/semanticRef.schema");
const { Schema } = mongoose;

const ReviewEventSchema = new Schema({ action: { type: String, enum: ["review_requested", "review_withdrawn", "changes_requested", "published"], required: true }, actorUserId: { type: Schema.Types.ObjectId, ref: "User", required: true }, at: { type: Date, required: true }, message: { type: String, trim: true, default: null } }, { _id: false });
const ReviewSchema = new Schema({ requestedAt: { type: Date, default: null }, requestedBy: { type: Schema.Types.ObjectId, ref: "User", default: null }, reviewedAt: { type: Date, default: null }, reviewedBy: { type: Schema.Types.ObjectId, ref: "User", default: null }, decision: { type: String, enum: ["pending", "approved", "changes_requested", null], default: null }, message: { type: String, trim: true, default: null }, events: { type: [ReviewEventSchema], default: [] } }, { _id: false });
const PlaceTypeSchema = new Schema({ key: { type: String, required: true, trim: true, lowercase: true }, label: { type: String, required: true, trim: true }, description: { type: String, trim: true, default: "" }, userIntents: { type: [{ type: String, trim: true, uppercase: true }], default: [] }, semanticRefs: { type: [SemanticRefSchema], default: [] } }, { _id: false });
const RoutingAttributeSchema = new Schema({ key: { type: String, required: true, trim: true, lowercase: true }, label: { type: String, required: true, trim: true }, description: { type: String, trim: true, default: "" }, dataType: { type: String, enum: ["boolean", "number", "string", "choice"], required: true }, unit: { type: String, trim: true, default: null }, options: { type: [{ type: String, trim: true }], default: [] }, canonicalKey: { type: String, trim: true, lowercase: true, default: null }, appliesTo: { type: String, enum: ["connection", "place", "both"], default: "connection" } }, { _id: false });
const RoutingRequirementSchema = new Schema({ attributeKey: { type: String, required: true, trim: true, lowercase: true }, operator: { type: String, enum: ["eq", "neq", "gte", "lte", "gt", "lt", "in"], default: "eq" }, value: { type: Schema.Types.Mixed, required: true }, priority: { type: String, enum: ["required", "preferred"], default: "preferred" }, weight: { type: Number, min: 0, default: 1 } }, { _id: false });
const RoutingPresetSchema = new Schema({ key: { type: String, required: true, trim: true, lowercase: true }, label: { type: String, required: true, trim: true }, description: { type: String, trim: true, default: "" }, requirements: { type: [RoutingRequirementSchema], default: [] } }, { _id: false });
const FloorSchema = new Schema({ key: { type: String, required: true, trim: true, lowercase: true }, label: { type: String, required: true, trim: true }, map: { imageUrl: { type: String, trim: true, default: null }, width: { type: Number, min: 1, default: null }, height: { type: Number, min: 1, default: null } } }, { _id: false });
const PlaceSchema = new Schema({ typeKey: { type: String, required: true, trim: true, lowercase: true }, label: { type: String, required: true, trim: true }, floorKey: { type: String, required: true, trim: true, lowercase: true }, position: { x: { type: Number, required: true, min: 0, max: 1 }, y: { type: Number, required: true, min: 0, max: 1 } }, attributes: { type: Schema.Types.Mixed, default: {} } }, { _id: true });
const ItemPlacementSchema = new Schema({ itemId: { type: Schema.Types.ObjectId, ref: "Item", required: true }, primaryPlaceId: { type: Schema.Types.ObjectId, required: true }, placeIds: { type: [Schema.Types.ObjectId], default: [] } }, { _id: false });
const ConnectionSchema = new Schema({ fromPlaceId: { type: Schema.Types.ObjectId, required: true }, toPlaceId: { type: Schema.Types.ObjectId, required: true }, directionality: { type: String, enum: ["directed", "bidirectional"], default: "bidirectional" }, distanceMeters: { type: Number, required: true, min: 0.1 }, additionalDelaySeconds: { type: Number, min: 0, default: 0 }, attributes: { type: Schema.Types.Mixed, default: {} }, instructions: { forward: { type: String, trim: true, default: null }, backward: { type: String, trim: true, default: null } } }, { _id: true });

const MuseumLayoutRevisionSchema = new Schema({ layoutId: { type: Schema.Types.ObjectId, ref: "MuseumLayout", required: true, index: true }, version: { type: Number, required: true, min: 1 }, basedOnRevisionId: { type: Schema.Types.ObjectId, ref: "MuseumLayoutRevision", default: null }, placeTypes: { type: [PlaceTypeSchema], default: [] }, routingAttributes: { type: [RoutingAttributeSchema], default: [] }, routingPresets: { type: [RoutingPresetSchema], default: [] }, floors: { type: [FloorSchema], default: [] }, places: { type: [PlaceSchema], default: [] }, itemPlacements: { type: [ItemPlacementSchema], default: [] }, connections: { type: [ConnectionSchema], default: [] }, preVisitInformation: { type: [{ type: String, trim: true }], default: [] }, status: { type: String, enum: ["draft", "in_review", "changes_requested", "published", "superseded"], default: "draft", index: true }, integrity: { status: { type: String, enum: ["valid", "needs_review"], default: "needs_review" }, issues: { type: [IntegrityIssueSchema], default: [] }, checkedAt: { type: Date, default: null }, checkedBy: { type: Schema.Types.ObjectId, ref: "User", default: null } }, review: { type: ReviewSchema, default: () => ({}) }, publication: { publishedAt: { type: Date, default: null }, publishedBy: { type: Schema.Types.ObjectId, ref: "User", default: null } }, createdBy: { type: Schema.Types.ObjectId, ref: "User", required: true }, updatedBy: { type: Schema.Types.ObjectId, ref: "User", required: true } }, { timestamps: true });
MuseumLayoutRevisionSchema.index({ layoutId: 1, version: 1 }, { unique: true });
module.exports = mongoose.model("MuseumLayoutRevision", MuseumLayoutRevisionSchema);
